[package]
name = "sudoku"
description = "A sudoku solver library"
license = "AGPL-3.0"
repository = "https://github.com/emerentius/sudoku"
documentation = "https://docs.rs/sudoku"
version = "0.4.0"
authors = ["Emerentius"]

[dependencies]
rand = "0.3.18"