[package]
name = "sudoku"
description = "A sudoku solver library"
license = "AGPL-3.0"
repository = "https://github.com/emerentius/sudoku"
documentation = "https://docs.rs/sudoku"
version = "0.4.1"
authors = ["Emerentius"]

[dependencies]
rand = "0.3.18"
serde = { version = "1.0.27", optional = true }

[dev-dependencies]
criterion = "0.1.2"

[[bench]]
name = "criterion"
harness = false