[package]
name = "sudoku"
description = "A sudoku solver library"
license = "AGPL-3.0"
repository = "https://github.com/emerentius/sudoku"
documentation = "https://docs.rs/sudoku"
version = "0.3.0"
authors = ["Emerentius", "Adolfo Ochagavía <aochagavia92@gmail.com>"]
